readme.md

Adds my website to the list.
Also, if you ever need help mantaining this (the community it's awesome), I'll be here to help :smile:

Add my website

---

contributing.md

This repo will follow the same community guidelines as Tailwind CSS does.

add reference to community guidelines

---

readme.md

I'm not sure if it belongs in this list, but someone requested if I wanted to add it to this list.

Add Ruby on Rails example project

---

readme.md

Appends a starter kit I created for using Tailwind with Jekyll.

Add Tailwind Jekyll Starter Kit

---

readme.md

This PR adds [Webslides](https://slides.zone) to the list

Add I project I made during the weekend

---

readme.md

TBH I'm really having hard time deciding whether this fits better in Resources, open source projects or apps (or demos, to be frank :D), so for now I'm adding it as is. Cheers.

Add Tailwind Fiddle.

---

readme.md

This PR adds @rias500 website. Discovered on [Built With Tailwind](builtwithtailwind.com).

Add @rias500's website

---

readme.md

https://github.com/awssat/tailwindo

added bootstrap-to-tailwind converter

---

readme.md

https://murze.be, open source at https://github.com/spatie/murze.be

Add @freekmurze's website (murze.be)

---

readme.md

Tailwindcomponents.com is a repository for community components

add tailwindcomponents.com

---

readme.md

Added Creating a modal dialog with Tailwind CSS tutorial by m2de

Added Creating a modal dialog with Tailwind CSS

---

readme.md

I recently created a really simple Jekyll theme from the ground up using Tailwind for my personal site, so figured I'd post it here.  I really enjoyed fine-tuning the responsiveness of it using Tailwind.  👍

Add @joeybeninghove Jekyll site, designed with Tailwind

---

readme.md

Adds several articles written by Nick Basile about getting started with and using Tailwind.

Added several how-to articles

---

readme.md

Added my website

---

readme.md

I have simple project using tailwindcss to create Wordpress Theme and implement New Technology (PWA)
thank you very much sir @merchedhq
regards
@ri7nz

Want to contribution

---

readme.md

Made an toggle switch

---

readme.md

Add https://css-cursors.netlify.com/

Add CSS Cursors to Websites category

---

contributing.md
readme.md

Now that plugins have officially been released it is probably a good idea to have a specific section for those.
Also small update to the contributing document to try and keep it inline with the repo.

Added Plugins specific section and updated Contributing doc

---

readme.md

I started working on a version of CRNA styled using Tailwind tonight. The repo is currently usable, but there's still _a lot_ of work to do. If anyone wants to help out, that would be incredible. 🙌

Add Create React Native App Tailwind

---

readme.md

I created a Gatsby starter that uses Tailwind today.

Add Gatsby Starter Tailwind

---

readme.md

Added the Tools section

---

readme.md

Add Create React App Tailwind

---

readme.md

Rebuild Twitter
Rebuild YouTube
Transitions Plugin

Add YouTube screencasts and a plugin

---

readme.md

This PR adds a couple plugins I've just published to npm to the list.

Add new plugins to readme.md

---

readme.md

https://github.com/comfusion/seminyak
https://themes.gohugo.io/theme/seminyak/

Add Hugo Theme

---

readme.md

added ournameismud.co.uk to apps/websites

---

readme.md

Built with Tailwindcss, Vue.js and RoR

Added personal portfolio

---

readme.md

This PR add a couple of plugins of mine plus @hendrikeng's `object-fit`.

Add new plugins to the list

---

readme.md

Added some websites to the examples section and Alfred Workflow to tools section.

Website examples and Alfred Workflow

---

readme.md

We just added Tailwind as a frontend preset for Sage.

Add Sage – WordPress starter theme

---

contributing.md
readme.md

* Consistent and correct usage of "Tailwind CSS"
* Added entity exemption to license

 Consistent and correct naming

---

readme.md

Hi, 
Hope i've done this right, it's the first time i've tried this! :)

Added Tailwind Toolbox links

---

readme.md

Added some website examples I have built.

Added some built with TailwindCSS website

---

readme.md

It was great fun and a huge productivity boost. ❤️ 
I think it checks both guidelines
- The website is available without errors or ssl certificate problems, and load in a reasonable amount of time.
- The website is using Tailwind intensively.

Our first tailwind site in production

---

readme.md

Hey!
This PR adds a new item to the open-source list. It differs from the other create-react-app items in the list as it adds `TailwindCSS` to the react-scripts itself. This way it is even possible to add `PurgeCSS` for production builds.
To create a new project:
```bash
npx create-react-app --scripts-version=react-scripts-tailwindcss my-app
```

Add create-react-app item

---

readme.md

- suyalcinkaya.me (my portfolio website) added.

New website

---

readme.md

Add how to setup TailwindCSS in Phoenix 1.4

---

readme.md

Two sites I've recently (re)built using Tailwind.

OpenEmu + Checkbox Toggle

---

readme.md

It's a personal site where I've been publishing short fictional writings for 15 years. Initially built with `nanoc` and `less`. Recently rewritten with `jigsaw` and `tailwindcss`.

Add sleeplessmind.info

---

readme.md

- Tool to interactively create button and copy classes
- Live: https://minthemiddle.github.io/tailwind-button-playground/
- Repo: https://github.com/minthemiddle/tailwind-button-playground

Add: Tool Tailwind Button Playground

---

readme.md

tailwind-themes.com doesn't seem to exist any more

remove Tailwind Themes dead link

---

readme.md

wasn't sure which category this belonged in, so let me know if it needs to be moved around

add Tailwind Dark Mode Theme Switcher

---

readme.md

This PR adds a simple starter I made for styling Next apps with Tailwind.

Add Tailwind Next.js Starter

---

readme.md

Vue tailwind is a set of vue components that with customizable Tailwind Classes:
https://vue-tailwind.com/

Add vue-tailwind

---

readme.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aniftyco/awesome-tailwindcss/152)

Fix Components & Libraries order

---

readme.md

I think this fits best under resources. Let me know if I should change^^

Add Figma Kit to resources

---

readme.md

Added a new website - Hunsbury Hot Tubs
Updated website - Woburn Mosaic
Removed Website - Natures Finest Pet Supplies Holding Page - as now dead.

Update to websites using Tailwind

---

readme.md

Plugin for style generation and more (tba)
Demo:

Add Figma Plugin to Tools

---

readme.md

Thanks for putting this list together! :zap:

Add BuildPulse to apps using Tailwind

---

readme.md

Added a new Resource - Tailwind cheatsheet.
https://umeshmk.github.io/Tailwindcss-cheatsheet

Added 'Tailwindcss Cheatsheet' to Resources

---

readme.md

I added [tailwindcss-theming](https://github.com/hawezo/tailwindcss-theming), which is a plugin that allows client-side theming thanks to CSS variables.

Added tailwindcss-theming

---

readme.md

Barebones example of setting up TailwindCSS with Webpack and PostCSS for a new project.

Add my blog post of setting up tailwind

---

readme.md

- Add typed-tailwind: More safe/confident to use TailwindCSS in TypeScript
- Add re-tailwind: More safe/confident to use TailwindCSS in ReasonML

Add re-tailwind & typed-tailwind

---

readme.md

- [Re-create Airbnb’s Home Page with Tailwind CSS](https://web-crunch.com/re-create-airbnbs-home-page-with-tailwind-css/)
- [Let’s Build: With Tailwind CSS – Movie Production Landing Page](https://web-crunch.com/tailwind-css-movie-production-landing-page/)
- [Lets Build: With Tailwind CSS – Responsive Navbar](https://web-crunch.com/lets-build-tailwind-css-responsive-navbar/)
- [Let’s Build: with Tailwind CSS Dribbble Shot](https://web-crunch.com/lets-build-tailwind-css-dribbble-shot/)
- [Let’s Build: With Tailwind CSS – Tweet](https://web-crunch.com/lets-build-tailwind-css-tweet/)
- [How to Extend Tailwind CSS](https://web-crunch.com/how-to-extend-tailwind-css/)

Add 6 new demos

---

readme.md

As a thank you to Adam and Steve for all the work they do on Tailwind, this section of the docs will be purely for featuring something beneficial to the community that they are building. Sorta of like an ad, but for only Tailwind stuff.
Also prettier formatted the doc on save, lol.

Add tailwind ui notice

---

readme.md

https://github.com/impulse/gatsby-typescript-tailwind

Add gatsby-typescript-tailwind to starters

---

readme.md

Added Headwind to README.md

---

readme.md

For consistency with the other descriptions.

Fix #191 syntax

---

readme.md

Added line in the tools section:
🔧 Protoship Codegen - Code generator that creates Tailwind CSS based HTML & CSS from Sketch designs.

Add new tool: Protoship Codegen

---

readme.md

Add https://moodz.yakovleva.dev to the list of websites

Add MOODZ to the list of websites

---

readme.md

Laravel livewire is made with a tailwindcss and I added it into the list.

Added Laravel Livewire

---

readme.md

Tailwind Starter Kit is an extension for TailwindCSS, Free and Open Source.

Added Tailwind Starter Kit

---

readme.md

In this repo, I rebuild UIs of Shopify, Spotify, Netlify, and Atlassian using Tailwind.css.

Add a link which showcases a list of realworld UIs using Tailwind

---

readme.md

Valohai site is styled entirely in Tailwind.

docs - Add Valohai site

---

readme.md

- Add Spotify Cast
- Add Discord Cast
- Add Meetup Cast

Add Andre Madarang Tailwind CSS cast

---

readme.md

Recently moved over to tailwind css.
myDID is the client for passwordless authentication service https://did.app

Add mydid to the Apps and Websites section

---

readme.md

Project contains:
- The project uses Eleventy as a static site generator
- Default templating is Nunjucks
- PostCSS set up to handle:
- TailwindCSS
- Autoprefixer
- PurgeCSS to remove unused CSS (set up for TailwindCSS by default) in production
- HTML minified in production
- CSS inlined and minified in production
- Webpack used to bundle scripts
- Scripts optimised for production
- Document <head> crafted using htmlhead.dev

Add JAMStack Web Starter kit (Eleventy based)

---

readme.md

Remove full.snack.dev

---

readme.md

I made this simple plugin which works with Tailwind 1.2, it will combine all your colors with your opacity settings and generate the corresponding rgba colors.

Add `tailwind-color-alpha`

---

readme.md

Hello 👋 
I added the Tailwind CSS module made for NuxtJS, as well as the official documentation which is using Tailwind too :)

Add @nuxtjs/tailwindcss and nuxtjs.org

---

readme.md

Added 2 opensource projects and 1 website

Add `SapperCommerce`, `Misiki Books` and `Litekart`

---

readme.md

Hi, I would like to propose one more plugin to this list.

Added tailwindcss-tooltip-arrow-after

---

.github/workflows/lint.yaml
readme.md

The creator of `awesome-lists` has released a tool for [linting awesome-lists](https://github.com/sindresorhus/awesome-lint) before they can be added to the parent [awesome-list](https://github.com/sindresorhus/awesome).
This PR brings the README up to the rigorous standard of the linting tool. There are some items that only the GitHub repo owners can perform such as updating the repo Topics.
Fixed issues:
~Outstanding issues:~
<details>
<summary>not valid</summary>
```
✖  1:1  The repository should have "awesome" as a GitHub topic       remark-lint:awesome-github
✖  1:1  The repository should have "awesome-list" as a GitHub topic  remark-lint:awesome-github
```
</details>

awesome-list compliance update

---

readme.md

This is a website that I've made to inspire folks to do something fun this month. Made during the covid-19 pandemic for folks who are at home and may appreciate some inspiration. The website is fully collaborative, folks can add ideas via github.

Added this-month-rocks

---

readme.md

Dumpsters.com is a huge site that utilizes tailwind on most of its pages. (Disclaimer - I work for Dumpsters.com)

Added dumpsters.com to README

---

readme.md

Added a link to a plugin i created: [tailwindcss-rtl](https://github.com/20lives/tailwindcss-rtl)

Adding tailwindcss-rtl link

---

readme.md

Created a repository for this project. The links are updated.

Update Tailwind Blocks

---

readme.md

A previous PR used `+` as a bullet, but `-` is enforced, so CI is now failing.

Fix style to pass CI

---

readme.md

Hello :wave:
I added the Datepicker for Vue.js component using Tailwind CSS.
Thank you :blush:

add vue-tailwind-picker component

---

readme.md

Remove a double space and add an empty line before a title.

Prettify README

---

readme.md

added pwainside in app & websites
[PWA Inside](https://pwainside.com)

added pwainside in app & websites

---

readme.md

Add [Tailwind CSS Shades](https://github.com/bourhaouta/vscode-tailwindshades)

Add Tailwind CSS Shades

---

readme.md

Sail UI is a collection of basic UI components built on Tailwind CSS.

Add Sail UI

---

readme.md

Tailwindow is a component viewer and collection of Tailwind CSS. More component will be added

Add Tailwindow

---

readme.md

Generator for shades color with customizable interval and range color [https://color.tailwindow.com](https://color.tailwindow.com)

Add Tailwindow Color Shades Generator

---

readme.md

Add the equalopportunity.work job board to the list of websites

Add equalopportunity.work to Apps and Websites

---

readme.md

It's technically a plugin but has lots of components unlike other plugins, so I added it in the "UI Libraries & Components" section. Hope that's okay.

Added Kutty Component Library Plugin

---

readme.md

Add [Tailwind Config Viewer](https://github.com/rogden/tailwind-config-viewer) to Tools

Add Tailwind Config Viewer to Tools

---

readme.md

Added GPT-3 Tailwind CSS code generator

Added GPT-3 Tailwind CSS code generator

---

readme.md

This PR "fixes" the last issue with CI by removing the `double-link` rule, which was, for some reason, failing on the `#plugins` table of content link. 
I also made some minor changes that I didn't catch during pull requests. These changes are syntax and grammar fixes, and a bit of rephrasing.

Fix CI and add minor changes

---

readme.md

Adds [tailwindcss-padded-radius](https://github.com/locksten/tailwindcss-padded-radius).

Add tailwindcss-padded-radius plugin

---

readme.md

Added Gatsby starter (https://github.com/PlanFlowDev/Simplicity-Itself-Gatsby-Tailwind-Starter-Theme).

Add Gatsby Starter Simplicity

---

readme.md

Not sure if that's the right category but couldn't find anything else that fit. Happy to move it to another one or create one if you want me to.

Add Tailwind Weekly

---

readme.md

This adds my theming plugin `tailwindcss-theme-variants` ([GitHub](https://github.com/JakeNavith/tailwindcss-theme-variants) / [NPM](https://www.npmjs.com/package/tailwindcss-theme-variants)). Hope the description is the right balance of informative and concise.
👍 Thanks for maintaining this list!

Add `tailwindcss-theme-variants`

---

README.md

Removed a couple more not-so-awesome sites, added better descriptions for them and put mine back.

refactor: change site descriptions & add mine back

---

README.md

| Tailwind Color Explorer | [https://stefanbuck.com/tailwind-color-theme-explorer](https://stefanbuck.com/tailwind-color-theme-explorer) |
This is a tool I wrote primally for myself to tinker with different colors in isolation from a project.
---

add(tools): Tailwind Color Explorer

---

README.md

| Tailwind Typography Playground | https://tailwind-typography-playground.vercel.app/ |
A little tool I wrote for myself to learn Tailwind CSS and quickly experiment to see how different Google font combinations would look when used with the Tailwind Typography plugin.
---

add(tools): Tailwind Typography Playground

---

README.md

| Tailwind Ink | https://tailwind.ink/ |
An interesting AI-based palette generator, trained with the Tailwind CSS color palette.
---

add(tools): Tailwind Ink

---

README.md

| Eleventy Starter Boilerplate | https://creativedesignsguru.com/demo/Eleventy-Starter-Boilerplate/ |
Add starter code for Eleventy static generator using Tailwind CSS for the styling part. I want to make it clear the boilerplate code doesn't provide a default theme but Tailwind CSS is correctly installed. The developper doesn't need to configure Tailwind CSS and he just need to start writing Tailwind classes into his HTML file.
---

add(starters): Eleventy Starter

---

README.md

| Leading Trim | https://github.com/stormwarning/tailwindcss-capsize |
Adds utilities to trim whitespace above and below text (using [Capsize](https://github.com/seek-oss/capsize)).
---

add(plugin): Capsize

---

README.md

| Name        |Link           | 
| ------------- |:-------------:|
| Tail-Animista    | https://tail-animista.vercel.app/ |
I built a tool for those Tailwind CSS users who are having hard times in importing animations provided by <a href="https://animista.net/">Animista</a> into tailwind's config file, here is the gif below for the basic usage.
<a target="_blank" rel="noopener noreferrer" href="https://raw.githubusercontent.com/vikrantyadav611/Vue-Resume/master/src/assets/tail-animista_1.gif"><img src="https://raw.githubusercontent.com/vikrantyadav611/Vue-Resume/master/src/assets/tail-animista_1.gif" alt="Sep-04-2020 23-33-08" style="max-width:100%;"></a>
---

add(tools): tail-animista

---

README.md

| Tails | https://github.com/thedevdojo/tails |
Tails is a (no-config) copy'n paste library of hand-crafted templates and components built in TailwindCSS.

add(libraries): tails

---

README.md

| Tailwind PLay | https://play.tailwindcss.com/ |
The new official Tailwind CSS playground. Absolutely awesome tool. I have added it in the Useful Links category, but also in the Tools one.
---

add(useful-links): Tailwind Play

---

README.md

| Hypercolor | https://hypercolor.dev |
Collection of pre-configured Tailwind CSS gradients with directional options.
---

add(tools): Hypercolor

---

README.md

| lofi ui | https://lofiui.co/ |
Low-fidelity Tailwind CSS components.
---

add(components): lofi ui

---

README.md

| prettier-plugin-tailwind | https://github.com/Acidic9/prettier-plugin-tailwind |
Prettier plugin that sorts a classlist based on tailwind plugins.
---

add(tools): prettier-plugin-tailwind

---

README.md

| tailwind-classes-sorter | https://github.com/Acidic9/tailwind-classes-sorter |
NPM library which provides a utility to sort tailwind classes.
---

add(tools): tailwind-classes-sorter

---

README.md

| Font Variant Numeric | https://github.com/philippbosch/tailwindcss-font-variant-numeric |
Font Variant Numeric is natively supported [since v1.8.0](https://tailwindcss.com/docs/font-variant-numeric)
---

update(plugins): deprecate Font Variant Numeric

---

README.md

| Gust UI | https://www.gustui.com/ |
Gust UI is a collection of components, elements, and pages for web applications in React and HTML.
---

add(libraries): Gust UI

---

README.md

| Palettolithic              | https://palettolithic.com                 |
Input one color and it will generate full color palette, 12 colors x 9 shades each, along with configuration code.
---
- [x ] My item is in the right category
- [ x] My item is logically grouped below similar items
- [x ] My item's name and description respects the conventions of the list
- [ x] My item is awesome
- [ x] I have read and followed the [contribution guidelines](.github/CONTRIBUTING.md)

add(tools): Palettolithic

---

README.md

| Simple Light | https://github.com/cruip/tailwind-landing-page-template |
Simple Light is a free landing page template built on top of TailwindCSS and fully coded in React.
---

add(templates): Simple Light

---

README.md

| Resume Template| https://github.com/mohusman360/mohusman360.github.io|
Simple Resume Template with Tailwind CSS
---

add(templates): Resume Template

---

README.md

| Jakarta LTE | https://github.com/zeroblack-c/jakarta-lte |
Free and Open Source Premium Admin Templates with rich UI Kit base on Tailwind CSS
---

add(templates): Jakarta LTE

---

README.md

| Headless UI | https://github.com/tailwindlabs/headlessui |
It's already in its right category, but I added it here as well for visibility, just like Tailwind Play, and because it's an official Tailwind Lab resource.
---

add(useful-links): Headless UI

---

README.md

|V-Dashboard|https://github.com/wobsoriano/v-dashboard |
|Vite + React + TailwindCSS Starter|https://github.com/wobsoriano/vite-react-tailwind-starter|
Add starter using Vite + React + Tailwind and a dashboard template using Vue 3 and Tailwind. 
---

add(starters): V-dashboard and Vite + React starter

---

README.md

| TailwindCSS Colors v2.0 Library | https://www.figma.com/community/file/905719775911766776|
Added TailwindCSS Colors v2.0 Library for Figma
---

add(tools): TailwindCSS Colors v2.0 Library for Figma

---

README.md

| Tailwind CSS Explorer for Code | https://marketplace.visualstudio.com/items?itemName=PeterMekhaeil.vscode-tailwindcss-explorer |
Add Tailwind CSS Explorer for Code
---

add(ide): Tailwind CSS Explorer for Code

---

README.md

| Vite + Vue 3.x + Tailwind 2.x Starter | https://github.com/web2033/vite-vue3-tailwind-starter |
Starter Template: `Vite + Vue 3 + Vue Router 4 + Tailwind 2`
Extra: `Vite Preset` was removed, 404.
---

add(starters): Vite + Vue 3.x + Tailwind 2.x

---

README.md

| Shopify Theme Lab | https://github.com/uicrooks/shopify-theme-lab |
Shopify Theme Lab is a customizable modular development environment for blazing-fast Shopify theme creation.
---

add(starters): Shopify Theme Lab

---

README.md

| _Colorkraken_ | _[Resource link here](https://www.npmjs.com/package/colorkraken)_ |
_Color Kraken is an hsl tailwind integration that generates custom color shades from a given hexcolor_
---
- [ +] My item is in the right category
- [ +] My item is logically grouped below similar items
- [+ ] My item's name and description respects the conventions of the list
- [+ ] My item is awesome
- [+ ] I have read and followed the [contribution guidelines](.github/CONTRIBUTING.md)

add(tools): Colorkraken

---

README.md

add(templates): Petra

---

README.md

| _Starter Dashboard Layout_ | _https://github.com/Kamona-WD/starter-dashboard-layout_ |
---

add(templates): dashboard layout

---

README.md

| Daisy UI | https://github.com/saadeghi/daisyui |
Themeable UI components library for Tailwind CSS.  
It has a styled version and an unstyled version.
Can be used via CDN or can be installed as a Tailwind CSS plugin.
- Github: https://github.com/saadeghi/daisyui  
- Demo: https://daisyui.netlify.app/  
- NPM: https://www.npmjs.com/package/daisyui
- Tailwind Playground to try it online: https://play.tailwindcss.com/hn9vnQsIn2
---

add(components): Daisy UI

---

README.md

| WickedBlocks | https://blocks.wickedtemplates.com/ |
Collection of more than 120 layout blocks and components built with Tailwind CSS V2 
---
-  [x] My item is in the right category

add(components): WickedBlocks

---

README.md

| babel-plugin-tailwind-dark | https://github.com/wowlusitong/babel-plugin-tailwind-dark |
A Babel plugin to add custom dark class when compiling your code using Babel. [example](https://tailwind-dark.vercel.app)
---

add(tools): babel-plugin-tailwind-dark

---

README.md

- 💼 [Text Decoration Color](https://github.com/ahmadawais/tailwind-text-decoration-color) - Adds `text-decoration-color` utility classes.
| Text Decoration Color | https://github.com/ahmadawais/tailwind-text-decoration-color |
---

📦 NEW: tailwind-text-decoration-color

---

README.md

| Line Clamp |https://github.com/tailwindlabs/tailwindcss-line-clamp |
Add new line clamp plugin created by Adam today.
---

add(plugin): Line Clamp

---

README.md

Which Provides utilities for styling lists and `<summary>` markers
| tailwindcss-marker | [GitHub](https://github.com/RadishIO/tailwindcss-marker) / [npmjs.com](https://www.npmjs.com/package/@radishio/tailwindcss-marker) |
Provides utilities for styling lists- and `<summary>` markers
---

add(plugins): tailwindcss-marker

---

README.md

| _Easy Tailwind_ | _https://easytailwind.now.sh |
---

add(templates): Easy Tailwind

---

README.md

| tailwind-caret-color | https://github.com/Naoray/tailwind-caret-color |
| tailwind-caret-color | https://github.com/GraxMonzo/tailwind-caret-color |
The original plugin is no longer maintained. New fork adds support for Tailwind 2.0 and custom variants
---

update(plugins): link to new `tailwind-caret-color` fork

---

.github/CONTRIBUTING.md

In respect to Tailwind Labs, Inc we want to make sure that anything that we hold in this repository also respects their brand usage guidelines.

chore(contributing): add brand usage guidelines requirement

---

README.md

| _themes.dev_ | _https://www.themes.dev/_ |
_Added link to main website, - offers free and premium Tailwind CSS themes and components. Added link to blog article about setting typographic defaults in Tailwind CSS_
---

add(templates): themes.dev

---

README.md

| create-tailwind-plugin | https://github.com/Landish/create-tailwind-plugin |
create-tailwind-plugin - Create Tailwind CSS plugin and publish on npm with ease
---

add(tools): create-tailwind-plugin

---

README.md

| @ngneat/tailwind | https://github.com/ngneat/tailwind |
Angular schematics that will integrate Tailwind CSS into Angular application.
---

add(tools): @ngneat/tailwind

---

README.md

| tailwind-direction | https://github.com/yassinebridi/tailwind-direction |
Tailwind bi-directionality plugin
---

add(plugins): tailwind-direction

---

.github/CONTRIBUTING.md
README.md

This PR remove the Apps & Website category, since we don't get PRs in this section, and that they're hard to accept anyway.

chore: remove Apps & Websites

---

README.md

| _tailwind-scrollbar-hide_ | _https://github.com/reslear/tailwind-scrollbar-hide_ |
_tailwindcss plugin for visual hide scrollbar_
---

add(plugins): tailwind-scrollbar-hide

---

README.md

| updrafts.app | https://updrafts.app/ |
An online no-code drag and drop editor to build Tailwind CSS based elements or full designs. The idea is similar to `tailwind play`, _(design online with instant feedback and sharable links)_, but instead of needing to write code, the user uses a drag-and-drop based interface and property pickers.
---

add(tools): updrafts.app

---

README.md

| Kometa UI Kit | https://kitwind.io/products/kometa/components |
Multi-purpose UI kit, built with Tailwind CSS.
It includes over 130 fully responsive sections.
Can be used on personal and commercial projects without attribution.
Available in:
- HTML
- VueJS
- React
---

add(components): Kometa UI Kit

---

README.md

| Mamba UI | [https://mambaui.com/](https://mambaui.com/) |
Free and open-sourced UI kit that has 50+ building blocks for Tailwind CSS projects. You can choose any of the 17 Tailwind CSS colors as the primary color, preview everything in light/dark themes and then export the code as HTML or JSX.
---

add(components): Mamba UI

---

README.md

| _How to create a responsive navigation menu in Tailwind CSS?_ | _https://www.themes.dev/blog/responsive-navigation-menu-tailwind-css/_ |
I will teach you how you can leverage Tailwinds utility classes to create a horizontal menu layout that transforms into a vertical hamburger style menu on smaller screen sizes.
---

add(learning): How to create a responsive navigation menu

---

README.md

| Wicked Templates |https://blocks.wickedtemplates.com|
Free code blocks
---

add(templates): Wiked Templates

---

README.md

| Downwind CSS Easings | https://github.com/downwindcss/easings |
Extends `transition-timing-function` utilities.
---

add(plugins): Downwind CSS Easings

---

README.md

| Web2Tailwind | https://web2tailwind.com |
Introduction to Tailwind CSS on how to build web components along with Alpine.js
---

add(learning): web2tailwind

---

README.md

| Content Placeholder | https://github.com/javisperez/tailwindcontentplaceholder |
Adds utilities for Content Placeholder images.
---

add(plugins): Content Placeholder

---

README.md

| Twind | https://github.com/tw-in-js/twind |
Compiler functions that turn tailwind classes into CSS at run, serve and build time. Enables efficient build step-less development with Tailwind. Find out more about Twind at https://twind.dev.
---

Adds Twind

---

README.md

| Windi CSS | https://github.com/windicss/windicss |
Windi CSS is a Tailwind CSS compatible library that focuses on compilation speed.
---

add(tools): Windi CSS

---

README.md

| Litepie Datepicker | [https://github.com/kenhyuwa/litepie-datepicker](https://github.com/kenhyuwa/litepie-datepicker) |
Litepie Datepicker is a date range picker component for Vue.js and Tailwind CSS, dependent to day.js.
---

add(component): Litepie Date Picker

---

README.md

| Just-in-time | https://github.com/tailwindlabs/tailwindcss-jit |
This PR adds a link to the new official just-in-time compiler.
- https://twitter.com/adamwathan/status/1371505992840663051
- https://www.youtube.com/watch?v=3O_3X7InOw8
---

add(links): Just-in-time compiler

---

README.md

Fix typo for the word "theme"

---

README.md

| Tailwind Cards | [https://github.com/hasinhayder/tailwind-cards](https://github.com/hasinhayder/tailwind-cards) |
Growing collection of text/image cards.
---

add(components): Tailwind Cards

---

README.md

add(templates): resume

---

README.md

| Tailwind CSS Variables | https://github.com/mertasan/tailwindcss-variables |
This plugin allows to configure CSS variables in the tailwind.config.js
---

add(plugins): Tailwind CSS Variables

---

README.md

| Tailwind CSS: From Zero to Production | https://www.youtube.com/playlist?list=PL5f_mz_zU5eXWYDXHUDOLBE0scnuJofO0 |
Playlist by Adam Wathan displaying a complete walkthrough of Tailwind CSS from Installation to Optimization for Deployment
---

add(learning): From Zero to Production

---

README.md

| _Ubuntu Desktop_ | _https://github.com/vivek9patel/vivek9patel.github.io_ |
---

add(open-source): Ubuntu Desktop

---

README.md

| Cookie - Jekyll Landing Website Starter | https://github.com/abhinavs/cookie |
Production ready, SEO-friendly, performant landing website boilerplate using Jekyll and Tailwind CSS.
---
- [ Y] My item is in the right category
- [Y ] My item is logically grouped below similar items
- [Y ] My item's name and description respects the conventions of the list
- [Y ] My item is awesome
- [Y ] I have read and followed the [contribution guidelines](https://github.com/aniftyco/awesome-tailwindcss/blob/master/.github/CONTRIBUTING.md)

add(Starters): Cookie

---

README.md

I did a rename on GitHub. This is just for fixing the links 👍🏻

fix: broken links due to my rename

---

README.md

| _Downwind CSS Text Decoration_ | _https://github.com/downwindcss/text-decoration_ |
Adds composable `text-decoration` utilities.
---

add(plugins): Text Decoration

---

README.md

| _Tailwindcomponents cheatsheet_ | _https://tailwindcomponents.com/cheatsheet_ |
_Tailwind CSS cheat sheet helps you to discover Tailwind CSS utilities_
---

add(tools): Tailwind Components' cheatsheet

---

README.md

| Gust | https://www.getgust.com|
Tailwind CSS drag and drop page builder for WordPress
---

add(tools): Gust, Tailwind CSS WordPress builder

---

README.md

| Tailwind Elements | https://tailwind-elements.com/|
Collection of free, popular components like modal, dropdown, carousel, popover, cards, charts and many more.
---

add(UI Library): Tailwind Elements

---

README.md

| create-next-pwa | https://github.com/msaaddev/create-next-pwa |
CLI that generates boilerplate code for Next.js Progressive Web App with integration of Tailwind.---

add(starter): create-next-pwa

---

README.md

| new-tailwind-app | https://github.com/msaaddev/new-tailwind-app |
Creates React.js, Next.js, Gatsby.js, Vue3, Laravel, and basic Tailwind CSS apps with a single command.
---

add(starter): new-tailwind-app

---

README.md

| _Tailwind CSS Gradient Generator_ | _https://tailwindcomponents.com/gradient-generator_ |
_Create perfect gradients for your Tailwind CSS sites easily with zero lines of code._
---

add(tools): Tailwind CSS Gradient Generator

---

README.md

| Vechai UI | https://www.vechaiui.com |
High-quality accessible React components with the built-in dark mode using Tailwind CSS.
---

add(ui-library): Vechai UI

---

README.md

| Tailwind Scroll Behavior | https://github.com/lukewarlow/tailwind-scroll-behavior |
Tailwind Scroll Behavior is a plugin that provides `scroll-smooth` and `scroll-auto` classes, to control smooth scrolling.
---

add(plugins): `tailwind-scroll-behavior`

---

README.md

| Tailwindcss Perspective | https://github.com/Kamona-WD/tailwindcss-perspective |
---

add(plugins): tailwindcss-perspective

---

README.md

| Tailmin | https://github.com/otezz/tailmin|
---

add(templates): Tailmin admin dashboard

---

README.md

| jekyll-tailwindcss-starter | https://github.com/shenlu89/jekyll-tailwindcss-starter |
A dead simple, comprehensive Jekyll boilerpalte styling with Tailwind CSS.
- Integrated with [Tailwind CSS](https://tailwindcss.com/) v2.2+, including [PostCSS](https://postcss.org/), [PurgeCSS](https://purgecss.com/)
- Compatiable with **Mordern Browsers** except **IE 11+**
- **Syntax Highlighting** with [Typography](https://github.com/tailwindlabs/tailwindcss-typography)
- Commenting support powered by [Disqus](https://disqus.com/)
- Optimized for search engines.
- Support **Google Analytics**
- **Latex** syntax through [Mathjax](https://www.mathjax.org/)
---

add(starter): Jekyll Starter

---

README.md

| Windframe | https://www.devwares.com/windframe/ |
---
Tailwind CSS drag and drop builder to rapidly build and prototype websites.

add(tools): Windframe

---

README.md

| Fluid Type | https://github.com/davidhellmann/tailwindcss-fluid-type |
Adds fluid type (`font-size`) utilities.
---

add(plugin): Fluid Type

---

README.md

| Next JS Boilerplate | https://creativedesignsguru.com/demo/Nextjs-Boilerplate/ |
Add starter code for Next JS using Tailwind CSS for the styling part.
---

add(starters): Add Next JS Boilerplate

---

README.md

| OhMySMTP Templates|https://github.com/ohmysmtp/templates|
A set of Transactional HTML Email Templates, built with Tailwind CSS and Maizzle
---

add(templates): OhMySMTP

---

README.md

| Tailwind Datepicker| https://github.com/themesberg/tailwind-datepicker |
A datepicker component built with Vanilla JavaScript and Tailwind utility classes.
---
| Flowbite| https://flowbite.com/docs/getting-started/introduction/ |
Open-source web components and interactive elements built with Tailwind CSS
---

add: datepicker plugin and Flowbite

---

README.md

| Flowrift | https://flowrift.com |
Beautifully designed Tailwind CSS UI blocks.
---

add(tools): Flowrift

---

README.md

| _Tailwind Typeahead_ | _https://github.com/basarozcan/vue-tailwindcss-typeahead_ |
_Typeahead/Autocomplete component built with Vue.js and Tailwind CSS_
---

add vue-tailwindcss-typeahead component

---

README.md

| clb | https://github.com/crswll/clb |
clb (class list builder) is a small, utility function that builds a class list based on a simple api.
It's like classnames and Stitches made a really lazy baby. It works really well with tailwindcss but will work with any functional / utility / atomic css approach.
---

add(tools): clb

---

README.md

| Red Pixel Themes | https://redpixelthemes.com/ |
I'm changing the old domain to the new one.
---

Rename Tailwind Made to Red Pixel Themes

---

README.md

| _Layouts for Tailwind_ | _https://layoutsfortailwind.lalokalabs.dev/_ |
_Layouts and UI Patterns for Tailwind CSS_
---

add(Components): Layouts for Tailwind

---

README.md

| tailwindcss-radix | [Link](https://github.com/ecklf/tailwindcss-radix) |
Plugin that adds utilities and variants for styling Radix UI state
---
> ^ Entries seem to be grouped by the number of categories. 
> Feel free to let me know if I should move the entry somewhere else.

add(plugins): tailwindcss-radix

---

README.md

| _Tailwind CSS Themeable_ | _https://github.com/upupming/tailwindcss-themeable_ |
---

add(plugins): `tailwindcss-themeable`

---

README.md

| Admin One Vue 3 | https://github.com/justboil/admin-one-vue-tailwind |
Free Vue.js 3 Tailwind CSS admin template with Vite & Vue CLI support.
---

add(templates): Admin One Vue 3

---

README.md

| Tailwind CSS Figma UI Design Kit | [_Resource link here_](https://flowbite.com/figma/) |
Figma UI Design Kit for Tailwind CSS.
| Tailwind Cheat Sheet | [_Resource link here_](https://flowbite.com/tools/tailwind-cheat-sheet/) |
Tailwind CSS utility class names in a searchable interface.
---

add(flowbite): Figma design kit + Cheat Sheet tool

---

README.md

| tailwindcss-container-query | [_Resource link here_](https://github.com/dgknca/tailwindcss-container-query) |
A plugin that provides CSS Container Queries for tailwindcss.
---

add(plugins): tailwindcss-container-query

---

README.md

| HyperUI | https://hyperui.dev/ |
---

add(components): HyperUI

---

README.md

…ss variables and variants.
| tailwindcss-themer | https://github.com/RyanClementsHax/tailwindcss-themer |
Adds theming support for Tailwind CSS with css variables and variants.
---
- [ x ] My item is in the right category
- [ x ] I have read and followed the [contribution guidelines](https://github.com/aniftyco/awesome-tailwindcss/blob/master/.github/CONTRIBUTING.md)

add(plugins): tailwindcss-themer

---

README.md

| Vite + React + TypeScript + Tailwind 3.x starter | [GitHub](https://github.com/PDMLab/vite-react-typescript-tailwind-starter) |
GitHub Template for Vite, React + Tailwind 3.x + TypeScript.
---

add(starters): Vite React TypeScript Tailwind 3.x

---

README.md

|Cruip |https://cruip.com|
Beautifully designed HTML, React, and Vue.js templates.
---

add(templates): Cruip

---

README.md

| Snippets | [snippets.alexandru.so](https://snippets.alexandru.so/) |
Open source collection of animation snippets made for Tailwind CSS
---

add(components): Snippets

---

README.md

| Fancy Tailwind| https://fancytailwind.com/|
_Beautiful, responsive, reusable, free and premium React/JavaScript Tailwind CSS UI components._
_More than 700 components._
_Components with effects and animations. JavaScript included._
---

add(components): Fancy Tailwind

---

README.md

| @formkit/tailwindcss | https://github.com/formkit/formkit/tree/master/packages/tailwindcss |
Adds variants for input and form states for FormKit.
---

add(plugin): @formkit/tailwindcss

---

README.md

| Vite-Boot | [ https://vite-boot.netlify.app/](https://vite-boot.netlify.app/) |
Vite + Vue3 + TypeScript + Vue-Router4 + Pinia + Tailwind CSS + VueUse  Template.
---

add(starters): Add Vite-Boot

---

README.md

|_Angular Spotify_| _https://github.com/trungk18/angular-spotify_ |
_ Spotify client built with Angular, Nx Workspace and Tailwind CSS._
---

add(open-source): Angular Spotify

---

README.md

| Twined Components|[https://github.com/lowfront/twined-components](https://github.com/lowfront/twined-components)|
Extended component of a styled-components that prioritizes class names for use in Tailwind CSS.
I have completed the development of Typescript support and request it.
---

add(tools): twined-components

---

README.md

| GitProfile | https://github.com/arifszn/gitprofile |
Automatic portfolio builder based on GitHub profile built with React.js + Tailwind CSS.
---

add(open-source): GitProfile

---

README.md

| Ui Colors | https://uicolors.app/create |
Color palette generator for Tailwind CSS
---

Add uicolors.app

---

README.md

| Tailwind CSS Highlight | https://marketplace.visualstudio.com/items?itemName=ellreka.tailwindcss-highlight |
Highlight utilities. VSCode Extension.
---

add(ide): tailwindcss-highlight

---

README.md

| _tailwindcss-webpack-plugin_ | _https://www.npmjs.com/package/tailwindcss-webpack-plugin_ |
[Tailwind CSS](https://tailwindcss.com/) v3.0 has [Just-in-Time](https://tailwindcss.com/blog/tailwindcss-v3#just-in-time-all-the-time) mode enabled by default, which brings a huge performance improvement, but since classes are generated on demand based on your source code, adding some unused classes directly in DevTools is now impossible, which can be a bit annoying.
Fortunately, this plugin can help us try out any tailwind utilities in DevTools, and it's important to note that this plugin was inspired by [Windi CSS](https://windicss.org/integrations/webpack.html), and the name "Design in devtool"s …

add(tools): tailwindcss-webpack-plugin

---

README.md

| Xtend UI | https://xtendui.com/ |
Tailwind CSS components with advanced interactions and animations.
---

add(library): Xtend UI

---

README.md

| Headless UI Float | https://headlessui-float.vercel.app |
Easy floating the Headless UI components.
---

add(library): Headless UI Float

---

README.md

| _starter-lit-with-tailwind_ | _https://github.com/running-grass/starter-lit-with-tailwind_ |
_Vite + Lit + Tailwind CSS template_
---

add(starter): Lit with Tailwind CSS

---

README.md

| Impulse.dev | [https://impulse.dev](https://impulse.dev) |
UI editor for Tailwind and React that edits your code.
---

add(tool): Impulse.dev

---

README.md

| Hyphens Plugin | [Link to plugin's repo](https://github.com/vivgui/tailwindcss-hyphens) |
The current `hyphens` plugin hasn't been updated since 2019 and it's outdated (uses the old syntax for making plugins). I created a new one for a project and I think others could benefit from using it. 
---

update(plugins): change `hyphens` plugin

---

README.md

| AstroWind - Started template | https://github.com/onwidget/astrowind |
AstroWind is a free, open-source and production ready template to make a website using Astro and Tailwind CSS. 
It contains the essentials to start an Astro project with Tailwind CSS (blog, sitemap, dark mode, RSS, images and fonts optimization, SEO...) and stands out for having a perfect 100/100 score in Lighthouse (Performance, SEO, Accessibility and Best Practices) .
---

add(templates): AstroWind

---

README.md

| tailwindcss-full-bleed| [_Resource link here_ ](https://github.com/dgknca/tailwindcss-full-bleed)|
A plugin that provides utilities for extended backgrounds and borders.
---

add(plugin): tailwindcss-full-bleed

---

README.md

|Tailwindhelper | https://www.tailwindhelper.com/ |
A website that helps you visualize Tailwind CSS classes and also has a unit converter tool.
___

add(tools): Tailwindhelper

---

README.md

| tailwindcss-vite-plugin | https://www.npmjs.com/package/tailwindcss-vite-plugin |
[Tailwind CSS](https://tailwindcss.com/) v3.0 has [Just-in-Time](https://tailwindcss.com/blog/tailwindcss-v3#just-in-time-all-the-time) mode enabled by default, which brings a huge performance improvement, but since classes are generated on demand based on your source code, adding some unused classes directly in DevTools is now impossible, which can be a bit annoying.
Fortunately, this plugin can help us try out any tailwind utilities in DevTools, and it's important to note that this plugin was inspired by [Windi CSS](https://windicss.org/integrations/webpack.html), and the name "Design in devtool"s was also …

add(tools): tailwindcss-vite-plugin

---

README.md

| _Supertweak_ | _https://supertweak.dev_ |
_Visual devtools for Tailwind CSS_
---

add(tools): Supertweak

---

README.md

| Admin One React | https://github.com/justboil/admin-one-react-tailwind |
Free React.js Tailwind CSS admin template with Next.js & TypeScript.
---

add(templates): Admin One React

---

README.md

| Vanilla Components | [Resource link](https://vanilla-components.com)|
Vanilla Components
Build Better & Faster
A lightweight, flexible & customizable UI library for Vue 3, styled with Tailwind CSS.
---

add(library): Vanilla-Components

---

README.md

| react-with-class | https://github.com/antomics/react-with-class |
Utility function for creating primitive React components with a set of classes, props or variants.  
Note: It's not directly tailwind related, but it's very helpful and is designed to work well with tailwind-like utility classes.
I didn't add it to the bottom, because it's similar to the clb library and I believe it's better for them to be logically grouped together.
---

add(tools): react-with-class

---

README.md

| Sailboat UI | https://sailboatui.com/ |
Sailboat UI is a modern UI framework for Tailwind CSS
---

add(library) Sailboat UI

---

README.md

| Flowbite Admin Dashboard | [https://github.com/themesberg/flowbite-admin-dashboard](https://github.com/themesberg/flowbite-admin-dashboard) |
Flowbite Admin Dashboard is an open-source project built with Tailwind CSS and Flowbite that features charts, widgets, tables, CRUD layouts, modals, drawers that can help you quickstart a web application. It has over 15 example pages including product and user CRUDs, authentication pages, settings page, two dashboard layouts, and it has dark mode support.
---

add(templates): Flowbite admin dashboard

---

README.md

| _Tailscan_ | _Tailscan.com_ |
_Ultimate devtools for Tailwind CSS v3 with ability to convert CSS to Tailwind CSS classes_
---

add(tools): Tailscan

---

README.md

|  Sira UI  | _https://sira.riccox.com_ |
Customizable and accessible design system which provides TailwindCSS component class name library to build modern UI.
---

add(libraries): Sira UI

---

README.md

| RippleUI | https://www.ripple-ui.com/ |
Cleanest, modern and beatifull Tailwind CSS components.
---

add(library): RippleUI

---

README.md

| CSS to TailwindCSS converter | https://github.com/Jackardios/vscode-css-to-tailwindcss |
CSS to TailwindCSS 3.x converter extension for VSCode
---

add(ide): CSS to TailwindCSS converter

---

README.md

added NativeWind
| NativeWind | https://www.nativewind.dev/ |
_NativeWind uses [Tailwind CSS](https://tailwindcss.com/) as scripting language to create a universal style system for React Native. NativeWind components can be shared between platforms and will output their styles as CSS StyleSheet on web and StyleSheet.create for native._
---
Found out about NativeWind and @joshmanders forced me to create a PR 😄

add(components): NativeWind

---

README.md

| Angular Tailwind | https://github.com/luciano-work/angular-tailwind |
| Vue Resume | https://github.com/luciano-work/vue-resume |
Admin Dashboard Starter Kit, Angular and Tailwind CSS
Resume template developer with Tailwind CSS and Vue Js.
---

add(starters): Angular Tailwind and Vue Resume

---

README.md

| _fortezhuo.my.id_ | _https://github.com/fortezhuo/fortezhuo.my.id_ |
_Eye catching resume built with Astro & TailwindCSS_
---

add(templates): Astro Template

---

README.md

| Built At Lightspeed | https://builtatlightspeed.com |
Massive database of Tailwind templates, starters & UI kits.
---
- [ i think so? ] My item is in the right category
- [ x ] I have read and followed the [contribution guidelines](https://github.com/aniftyco/awesome-tailwindcss/blob/master/.github/CONTRIBUTING.md)

add: Built at lightspeed

---

README.md

| Statichunt | https://statichunt.com/tailwind-templates |
Open source directory of hand-picked free and premium Tailwind templates & Starters.
---

add(templates): Statichunt

---

README.md

| TailwindCSS 3D plugin | https://github.com/sambauers/tailwindcss-3d |
A plugin to add 3D transform utilities and animations.
---

add(plugins): tailwindcss-3d

---

README.md

chore: remove dead links

---

README.md

| Tailwind Grid Generator | https://www.tailwindgen.com/ |
Tailwind Grid Generator is a tool that helps developers easily create custom layouts using the Tailwind CSS.
---

add(tools): Tailwind Grid Generator

---

README.md

| Tailkits | [https://tailkits.com/](https://tailkits.com/) |
Curated Tailwind CSS components, templates, UI kits, resources, tools & more.
---

add(libraries): Tailkits

---

README.md

remove: tailzilla.app 

---

README.md

| Raycast Extension| https://www.raycast.com/vimtor/tailwindcss |
Search documentation, classes and colors from Raycast (like Alfred)
---

add(tools): Raycast extension

---

README.md

| _DivMagic_ | _DivMagic.com_ |
_Copy any web element and style as Tailwind CSS component_
---

add(tools): DivMagic

---

README.md

added Windstatic
| _Windstatic_ |_https://www.windstatic.com_ |
---
- [+] My item is in the right category
- [+] My item is logically grouped below similar items
- [+] My item's name and description respects the conventions of the list
- [+] My item is awesome
- [+] My item is in line with the [Tailwind brand usage guidelines](https://tailwindcss.com/brand#usage)
- [+] I have read and followed the [contribution guidelines](https://github.com/aniftyco/awesome-tailwindcss/blob/master/.github/CONTRIBUTING.md)

add(components): windstatic

---

README.md

| _TailwindFlex_ | _(https://tailwindflex.com)_ |
| _Astro Theme Cactus_ | _https://github.com/chrismwilliams/astro-theme-cactus_ |
---
- [+ ] My item is in the right category
- [ +] My item is logically grouped below similar items
- [ +] My item's name and description respects the conventions of the list
- [ +] My item is awesome
- [ +] My item is in line with the [Tailwind brand usage guidelines](https://tailwindcss.com/brand#usage)
- [ +] I have read and followed the [contribution guidelines](https://github.com/aniftyco/awesome-tailwindcss/blob/master/.github/CONTRIBUTING.md)

add: TailwindFlex & Astro Cactus

---

README.md

removed archived repos and dead webpage [stitches]
BTW
since there's no god place for talk, I might as well ask here:
what is your philosophy on removing projects, since Tailwind is in version 3 and there's a few of repos that are, well, no longer so awesome, since tailwind already has those features built in. in fact, some of them are already archived by their developers. maybe this repo should follow, and remove those?

chore: removed some dead projects

---

README.md

I also put outdated  plugins in folded details/summary until you decide will they go out of list or what

chore : [removed some missing links]

---

README.md

| _Box Shadows Generator_ | _https://manuarora.in/boxshadows_ |
---
- [ + ] My item is in the right category
- [ +] My item is logically grouped below similar items
- [ +] My item's name and description respects the conventions of the list
- [ +] My item is awesome
- [ +] My item is in line with the [Tailwind brand usage guidelines](https://tailwindcss.com/brand#usage)
- [ +] I have read and followed the [contribution guidelines](https://github.com/aniftyco/awesome-tailwindcss/blob/master/.github/CONTRIBUTING.md)

adds Box Shadows Generator

---

README.md

Removed Broken Link!
https://kutty.netlify.app/

Removed Broken Link

---

README.md

| _Shadcn UI_ | _https://ui.shadcn.com_ |
_Re-usable components built using Radix UI and Tailwind CSS_
---
- [ x ] My item is in the right category
- [ x ] I have read and followed the [contribution guidelines](https://github.com/aniftyco/awesome-tailwindcss/blob/master/.github/CONTRIBUTING.md)

add(components): shadcn ui

---

README.md

Add STDF - Mobile web component library based on Svelte and Tailwind.
| STDF | https://stdf.design |
---

add(library): STDF

---

README.md

| EasyWind | https://github.com/avencera/easywind |
EasyWind is a CLI designed to be the easiest way to get started with TailwindCSS for static websites.
EasyWind is a tailwind project generator, tailwind compiler/watcher and a livereload server.
With EasyWind you don't need anything else, no need to download brew, node or even the standalone Tailwind CLI. If you don't have node, EasyWind will download the tailwind cli and use it.
---

add(tools): EasyWind

---

README.md

This PR removes any paid listings as per our discussion in https://github.com/aniftyco/awesome-tailwindcss/pull/531 about not wanting paid stuff on the list.
Lets hold this PR open for a few days and if anyone notices any more we can add to this before merging in.

Remove paid only listings

---

README.md

| _Ovidius_ | _[Repository link](https://github.com/JustGoodUI/ovidius-astro-theme)_ |
_Tailwind CSS & Astro.js blog template_
---

add(templates): Tailwind CSS and Astro

---

README.md

| Htmx | https://github.com/aniftyco/tailwind-htmx |
Add variants for styling [htmx](https://htmx.org/reference/#classes) events with Tailwind CSS
---

add(plugins): Htmx

---

README.md

Removing broken link to Tailwindsites.com

remove: tailwindsites.com

---

.github/CONTRIBUTING.md
README.md

As mentioned in #539 we will no longer have this section. Any project that UTILIZES Tailwind CSS but isn't a resource FOR Tailwind CSS can submit to the official [Showcase](https://tailwindcss.com/showcase).

remove(section): "Open Source Projects"

---

README.md

Added [Catalyst](https://tailwindui.com/templates/catalyst) to the list 👍

add(templates): Catalyst

---

README.md

| TWC | https://react-twc.vercel.app |
Lightweight library to create reusable React + Tailwind CSS components in one line.
---

add(library): TWC

---

README.md

| _Static Tailwind_ | _https://statictaliwind.com_ |
_The most used Tailwind CSS classes, without the build step_
---

Add Static Tailwind

---

README.md

| Name                 |Link                 |
|Dante | https://github.com/JustGoodUI/dante-astro-theme |
Minimal Astro.js + Tailwind CSS blog/portfolio theme 
---

add(template): Dante

---

README.md

Added Tremor to the Components/Library section.
| Tremor | https://tremor.so |
React library to build charts and dashboards with Tailwind CSS.
---

add(libraries): Tremor

---

README.md

| Gimli Tailwind | [_Resource link here_](https://chromewebstore.google.com/detail/gimli-tailwind/fojckembkmaoehhmkiomebhkcengcljl) |
A DevTools extension enabling smart tools for Tailwind CSS.
---

add(tools): gimli tailwind

---

README.md

| ska-tailwind-editor | https://sinukoduleheabi.ee/editor/|
A tool similar to Tailwind Playground (https://play.tailwindcss.com/) but instead of editing raw HTML you can convert it to WordPress blocks and edit Tailwind classes with UI.
---

add(tools): ska-tailwind-editor

---

README.md

Cleaning up broken links, fixing the contributing link in footer

chore: remove some broken links

---

README.md

| TailwindCssColors | tailwindcsscolors.com |
| TailwindGradients | tailwindgradients.com |
| Fullwind CSS| fullwindcss.com |
Color palete cheatsheet, gradient collection and extended shades for the default palette.
---

add(tools): tailwindcsscolors.com, tailwindgradients.com and fullwindcss.com

---

README.md

I changed my github username from luciano-work to lannodev

refactor: update github address

---

README.md

| Design GUI                 | Link                 |
| Design GUI|https://designgui.io|
AI-powered Chrome extension for managing colors in daisyUI and shadcn/ui.
---

add(tools): Design GUI

---

README.md

| Name                | Link                 |
| Indie UI | https://ui.indie-starter.dev/ |
Collection of cool UI components.
---

add(components): Indie UI

---

README.md

This fixes the linting issue we started to get recently (`remark-lint:no-undefined-references`)

chore: fix linting

---

README.md

| _Penguin UI_| _[Resource link here](https://www.penguinui.com/)_ |
Plug-n-play UI component library for Tailwind CSS & Alpine JS
---

add(components): penguin

---

README.md

| _Preline UI_ | _[Resource link here](https://preline.co)_ |
Preline UI is an open-source Tailwind CSS components library for any needs. Comes with UI examples & blocks, templates, plugins, Figma design system and more. For:  HTML React Vue 
---

add(components): Preline UI 

---

README.md

| Motion Primitives | https://motion-primitives.com |
Beautifully designed motion components built using Tailwind CSS and Framer Motion
---

add(components): Motion Primitives 

---

README.md

Clarify that components are for React in the description
| Motion Primitives | https://motion-primitives.com |
React motion components built with Tailwind CSS and Framer Motion.
---

update(motion-primitives): clarified the description

---

README.md

| _Flyon UI_ | _https://flyonui.com/_ |
[FlyonUI](https://flyonui.com/) is designed to combine the best of both worlds: the aesthetic appeal of semantic classes and the powerful functionality of JS plugins.
It has over 78+ components & examples & built with DaisyUI & Preline.
**Features:**
- 800+ Free Components & Examples
- Universal Framework Compatibility
- Unlimited Themes 
- Unstyled & Accessible Plugins
- Responsive & RTL support
- Free Forever
- Beautiful and Semantic Styling
- Efficiency and Productivity
- Maintainable and Scalable
---

add(library): Flyon UI

---

README.md

| InclusiveColors | https://www.inclusivecolors.com/ |
Create fine-tuned WCAG accessible Tailwind CSS color palettes, with previews on a live mockup
---
---
Hope the description isn't too long. I was trying to help describe what's different about its combination of features (fine-tuning instead of auto generation, focus on accessibility, and the live UI mockup preview to help with fine-tuning).

add(tools): InclusiveColors

---

.github/PULL_REQUEST_TEMPLATE.md

The PR updates the location of the contribution guidelines reference in PR template.
---

chore: update contribution guidelines reference

---

README.md

| CSS Variables Editor |https://www.cssvariables.com|
Rename Design GUI to CSS Variables Editor.
Description (hasn't changed):
AI-powered Chrome extension for managing colors in daisyUI and shadcn/ui.
---

Rename Design GUI to CSS Variables Editor

---

README.md

| Kokonut UI | https://kokonutui.com/ |
A collection of modern, interactive, customizable UI components
---

add(components): Kokonut UI

---

README.md

🕹️ **8bitcn** is an open-source collection of retro 8-bit styled UI components for React, built on top of [Shadcn UI](https://ui.shadcn.com/), [Tailwind CSS](https://tailwindcss.com/), and [Radix UI](https://www.radix-ui.com/).
Perfect for developers who love pixel art, nostalgic design, or want to add some playful vibes to their app.
- 🎮 8-bit themed components with pixel-art styling
- 🧱 Built with Radix UI primitives
- 🎨 Styled using Tailwind CSS
- ⚡ Easily customizable
- 🌍 Ready for modern React projects
👉 [8bitcn.com](https://8bitcn.com)

add(components): 8bitcn
