contributing.md
readme.md

Added to resources, because it helps developers use Tailwind in a specific dev environment. I noticed that the Tools category involved projects that only made use of Tailwind CSS, but were themselves useful for non-tailwind-development activities.

ng-tailwindcss

---

readme.md

We use this small tool to convert our collection Tailwindcss component snippet html files which mostly written prior to Tailwind version 1.0. It's already published into NPM for easy install and use.

add tailupgrade to convert html to v.1.0

---

readme.md

More details here: https://github.com/tailwindcss/tailwindcss/issues/1165
It's a tool to save you time when switching from using no prefix to using one. Or let's say you're using a prefix in your project and want to start using some tailwind component from the web that doesn't have a prefix, paste it in my tool and bam, you're ready to go

online tool to help you start using a prefix

---

contributing.md
readme.md

I think this repository needs some cleanup and reorganization. I'm obviously open to discussion about any modification I have made. :)
- It makes the contributor skip the `CONTRIBUTING` part at the end of the `README`. 
- It's very repetitive.
- [Webpack Starter Project](https://github.com/tailwindcss/webpack-starter) - Deprecated.
- [Adds Tailwind CSS to your Ember app or addon](https://github.com/embermap/ember-cli-tailwind) - Deprecated.
- [Create React Native App Tailwind](https://github.com/taylorbryant/crna-tailwind) - It's "work-in-progress" (last commit by a human 2 years ago).
- [Jaxli](https://github.com/laraboost/jaxli) - It's "still in development" (last commit 2 years ago).
- [Laraboost](https://laraboost.com) - No HTTPS and redirects to another domain.
- [Erik …

Clean-up: fixes, organization, descriptions

---

readme.md

Add https://github.com/vkaelin/LeagueStats to the list of open projects.
I was wondering 2 things:
- Should I post it in the websites list or in the open projects list ?
- Should I link to the homepage or directly to a player's page to have a better idea of the website (e.g. https://leaguestats.gg/summoner/euw/Alderiate)
Let me know and I will make the changes, thanks!

Add new Open Source project: LeagueStats

---

readme.md

https://github.com/hawezo/tailwindcss-scroll-snap 
I made this some time ago and it's useful to some people, so maybe it should be featured here. It's a simple plugin that adds `scroll-snap` utilities to Tailwind.

Add `tailwindcss-scroll-snap`

---

readme.md

As per their own [readme](https://github.com/hacknug/tailwindcss-cursor-extended), tailwindcss-cursor-extended is deprecated and can be implemented with base Tailwind, see [official plugin](https://tailwindcss.com/docs/cursor/#app).
So I moved it to the warning list :)

Move tailwindcss-cursor-extended to warning list

---

readme.md

Plugin for external services.
[preact-cli-tailwind](https://github.com/agneym/preact-cli-tailwind) - Adds Tailwind CSS module as PostCSS plugin and sets up PurgeCSS in production for PreactJS CLI Projects.

Add preact cli tailwind

---

readme.md

Hello!
I added "@tailwindcssinjs/macro" to the tools section.
Package description:
@tailwindcssinjs/marco is a babel macro that transforms Tailwind classes into css object styles. These css object styles can be used with your favorite css-in-js library.
Full disclosure: I am the author of this package.

Add "@tailwindcssinjs/macro"

---

readme.md

Hey! Sorry to create this extra overhead, but the "canonical" link for a17t's docs just changed, so I thought I'd update the list with the new URL.

Update a17t link

---

readme.md

Moved tailwind-color-alpha to old-plugins as 1.4 brings this into the core

moved tailwind-color-alpha to old-plugins

---

readme.md

Hi folks.
I added my [Create React App](https://create-react-app.dev/) (CRA) template, which you can use it with the CRA CLI (command line interface).
FYI - The linked template can be used like following.
```bash
npx create-react-app my-app --template tailwindcss-typescript
```

Added 'Create React App Template with Tailwind CSS + TypeScript'

---

readme.md

We use `Tailwind CSS` to refer to the framework, not `TailwindCSS`.

Fixed typos to match our guidelines

---

readme.md

Adds a link to [Create Tailwind CSS Boilerplate](https://github.com/michelegera/create-tailwindcss-boilerplate) to the “Starters, Templates & Themes” section.

Add Create Tailwind CSS Boilerplate

---

readme.md

Add “Open” landing page template by Cruip built with Tailwind CSS Boilerplate.

Add “Open” landing page

---

readme.md

Add [Tailwind CSS Multi Theme](https://tailwindcss-multi-theme.now.sh/) to plugins
and [Windmill Dashboard](https://windmill-dashboard.vercel.app/) to templates.
And I have a question: where would [Tailwind Starter Kit](https://tailwind-starter-kit.now.sh/) fit? It is a [library of components](https://tailwind-starter-kit.now.sh/docs/alerts), but it has also a [learning  guide](https://tailwind-starter-kit.now.sh/learn).
Should I place two entries, one for Learning (pointing to the guide) and one for Templates/themes (pointing to the components)? Or do you think there is a category which fits it?

Add Multi Theme and Windmill

---

readme.md

Tailwind Discussions repo moved to GitHub Discussions, this PR updates the link and description

docs: update discussions link

---

readme.md

In Tailwind 1.6.0, support for animations, including spin, was added. Here's an official example: https://tailwindcss.com/docs/animation/#spin

Move Spinner to Officially Implemented section

---

readme.md

This PR adds two of my presets: 
- [Vite + Tailwind CSS](https://github.com/use-preset/tailwindcss), which is a preset that adds Tailwind CSS to a Vite application (or creates the Vite application if required). It's useful for prototyping. 
- [Laravel Tailwind CSS](https://github.com/use-preset/laravel-tailwindcss), which is a preset that adds Tailwind CSS to a Laravel application. Under the hood, the [TALL](https://github.com/use-preset/laravel-tall) and [Inertia](https://github.com/use-preset/laravel-inertia) presets use that preset too (but I didn't add them to the list, seems out of scope).

Add Tailwind CSS presets

---

readme.md

Added link to Tailwind CSS bootstrap's flexbox grid [plugin](https://github.com/karolis-sh/tailwind-bootstrap-grid).

add Tailwind CSS bootstrap grid plugin

---

README.md

| Kevin Kirchner                 | https://github.com/kevnk                 |
| grayscale design | https://grayscale.design |
Create a custom color palette that maintains the same luminance (color value) from color to color. For example, changing from `blue-500` to `yellow-500` will have the same luminance (appearance of light or darkness). In other words, if you were to grayscale all the color palettes, they would all appear to be the same. 
Here's a video explaining how it works: https://www.loom.com/share/3efeb1820857480d8fd2ce74b712d223
---

Adding Grayscale Design color tool

---

README.md

| Tailwind CSS Filters | https://github.com/Larsklopstra/tailwindcss-css-filters |
This plugin adds CSS `filters` and `backdrop-filters` to Tailwind CSS with defaults.
Example:
```html
<div class="bg-white bg-opacity-25 bdf-blur-8 bdf-saturate-125">
...
</div>
```
---

add(plugin): CSS Filter & Backdrop Filter

---

README.md

Replace deprecated `@tailwindui/vue`, `@tailwindui/react` with `Headless UI`

update(libraries): Official unstyled UI components

---

README.md

I was too late for the review of https://github.com/aniftyco/awesome-tailwindcss/pull/319. I'm just fixing the name (for consistency, `TailwindCSS` vs `Tailwind CSS`) and its description for clarity. 
Thanks and sorry for the bother.

fix(tools): update name and description of Tailwind CSS v2 colors

---

README.md

| Aspect Ratio | https://github.com/tailwindlabs/tailwindcss-aspect-ratio |
| Forms | https://github.com/tailwindlabs/tailwindcss-forms |
This PR adds [Aspect Ratio]90, a new official plugin for adding composable aspect ratio utilities. 
It also deprecates [Custom Forms](https://github.com/tailwindlabs/tailwindcss-custom-forms), even though it's not yet deprecated, because [Forms](https://github.com/tailwindlabs/tailwindcss-forms) will be its successor. 
**Note**: I'm going ahead by deprecating Custom Forms in the list to make it clear that Forms is the new recommended plugin, but since it's not *yet* deprecated, feel free to ask me to un-deprecate it for now if you feel we should wait.
---

add(plugins): official Aspect Ratio and Forms

---

README.md

I updated the Gradient Designer to version 2, which also has all the colors from Tailwind 2.
A minor change has been done to the name. I removed "Tailwind" but it's still a gradient generator for Tailwind.

change(tools): update Gradient Designer name, url and description

---

README.md

This reverts adding Daisy UI as the link, repo, and user account seem to be 404 now.

remove(components): Daisy UI

---

README.md

| tailwindcss-rails | https://github.com/rails/tailwindcss-rails |
This is a new Ruby gem for using Tailwind CSS with Ruby on Rails' pipeline. For standard (configurable) use, Tailwind should still be installed with webpacker, but I thought this still belongs on the list.
More context: https://twitter.com/dhh/status/1349722147845976065
---

add(tools): tailwindcss-rails

---

README.md

| tailwindcss-pseudo-selectors | [github](https://github.com/Microwawe/tailwindcss-pseudo-selectors) / [npmjs](https://www.npmjs.com/package/tailwindcss-pseudo-selectors) |
A plugin that adds support for all the rest of the  (non-experimental) pseudo selectors from the [MDN documentation](https://developer.mozilla.org/en-US/docs/Web/CSS/Pseudo-classes) that Tailwind CSS doesn't have, such as `:valid` and `:invalid`. 
---

add(plugins): tailwindcss-pseudo-selectors

---

README.md

|Tailwind CSS plugin for removing scrollbars | https://github.com/redwebcreation/tailwindcss-no-scrollbar |
This plugin exposes a class that hides the browser's default scrollbar using various tricks
---

add(utilities): tailwindcss-no-scrollbar

---

.github/PULL_REQUEST_TEMPLATE.md

The link is broken in PRs because it is relative. Changed it to an absolute one.

fix(pr-template): update guidelines link

---

README.md

This PR deprecates three plugins related to the filter, backdrop-filter and blend-mode properties. These plugins have either been fully or partially implemented in the TailwindCSS core as of version 2.1.
---

chore: deprecate filter, backdrop-filter and blend-mode plugins

---

README.md

| Tailwind Accent Color | https://github.com/lukewarlow/tailwind-accent-color |
Tailwind Accent Color is a plugin used to generate [accent color classes / styles](https://drafts.csswg.org/css-ui-4/#widget-accent) with `accent-<color>`.
Right now this is only a feature in Chrome, and requires the user to activate a flag, though we'll likely see adoption pick up soon here. 
---

add(plugins): tailwind-accent-color

---

.github/PULL_REQUEST_TEMPLATE.md

I feel like this will prevent people from skipping the part that says "Please do not use the Tailwind name … in any way that could mistakenly imply any official connection with or endorsement of Tailwind Labs Inc." (or at least make it less likely).

feat(pr-template): explicitly add brand guidelines

---

README.md

Caret color utilities as well as a long list of pseudo selectors are included in tailwind v2.2.
I've left tailwindcss-pseudo-selectors as that package claims to and does seem to include a more exhaustive list of pseudo selectors than Tailwind does.
---

deprecate: `Caret Color` and `Pseudo`

---

README.md

| Capitalize first letter | https://github.com/riderx/capitalize-first-tailwind |
Tailwind plugin that adds utility for capitalize the first letter of the string.
Super useful when all your string come from i18n text and cannot be changed.
---

Add Capitalize first letter to plugin list

---

README.md

The [Vue Tailwind Picker](https://github.com/kenhyuwa/vue-tailwind-picker)  project now advises to use Litepie
---

remove(components): vue-tailwind-picker

---

README.md

This PR removes my plugin [`tailwindcss-scroll-snap`](https://github.com/innocenzi/tailwindcss-scroll-snap) which just got implemented in Tailwind CSS core.

remove(plugins): Scroll Snap

---

README.md

| _Inspect Flow_ | _inspectflow.io_ |
_Inspect Flow is a browser extension to quickly inspect, edit, and copy the Tailwind CSS classes of elements!._
---

add(tools): Inspect Flow

---

README.md

This PR moves a bunch of plugins that are now deprecated because of Tailwind v3 release (and some by additions in v2)

update: move plugins deprecated by Tailwind CSS v3

---

README.md

| Svelte Headless UI | [GitHub](https://github.com/rgossiaux/svelte-headlessui) |
_Unofficial Svelte port of Headless UI, the component library by Tailwind Labs that powers Tailwind UI_
---
Re: "my item is logically grouped below similar items", I think by that standard it should go closer to the main Headless UI entry. But I put it at the bottom of the library emoji list per the contribution guidelines. Up to you what to do about it.

add(libraries): Svelte Headless UI

---

README.md

|  tailwindcss-grid-areas |  https://github.com/SavvyWombat/tailwindcss-grid-areas |
Adds utilities for `grid-areas` and `grid-area`.
---
- [ x ] My item is in the right category
- [ x ] I have read and followed the [contribution guidelines](https://github.com/aniftyco/awesome-tailwindcss/blob/master/.github/CONTRIBUTING.md)

add(plugins): Grid Areas

---

README.md

| Tailiscope.nvim | https://github.com/danielvolchek/tailiscope.nvim |
Tailiscope nvim is a tool I built that converts the popular tailwind css cheatsheet format into a form that can be accessed directly within neovim as an extension to the very popular [telescope.nvim](https://github.com/nvim-telescope/telescope.nvim) plugin
---

add(tools): Tailiscope.nvim

---

README.md

| tailwindcss-accent   | [https://github.com/enjidev/tailwindcss-accent](https://github.com/enjidev/tailwindcss-accent) |
This plugin creates a dynamic accent color using CSS custom properties based on the Tailwind CSS default color palette.
It adds accent color utility classes to Tailwind CSS project, such as `bg-accent-500`, `dark:outline-accent-200`, etc.
It has been tested with Tailwind CSS versions 2 and 3.
---

add(plugins): tailwindcss-accent

---

README.md

Tailwind Elements is not exactly a library, you have to install it like a plugin, quoting from the official repo: "Tailwind Elements is a plugin that extends the functionality of the library with many interactive components.".
Also - it doesn't use any Bootstrap 5, it only recreates some components from Bootstrap 5 but it's not dependent on it.
I just fixed the categorization & the description.

fix(tailwind-elements): update description and category

---

README.md

It comes with Tailwind now
https://tailwindcss.com/blog/tailwindcss-v3-3#line-clamp-out-of-the-box

chore: deprecate line clamp plugin

---

README.md

| tailwindcss-filter-order | https://github.com/joshdavenport/tailwindcss-filter-order |
A plugin to order your CSS filters applied by Tailwind CSS. Order of filters passed to the filter property can drastically change the final result. Without use of this plugin filters are applied in the same order every time because Tailwind has a hardcoded order.
---
- [ x ] My item is in the right category
- [ x ] I have read and followed the …

add(plugins): CSS Filter Order

---

README.md

| 10 Tailwind CSS Tips and Tricks | https://www.youtube.com/watch?v=aSlK3GhRuXA |
10 Tailwind CSS tricks you should know.
---

add(learning - video): 10 Tailwind CSS tricks

---

README.md

Approved by Adam
https://twitter.com/adamwathan/status/1690029248734482432?s=20)
---
- [+ ] My item is in the right category
- [ +] My item is logically grouped below similar items
- [ +] My item's name and description respects the conventions of the list
- [ +] My item is awesome
- [ +] My item is in line with the [Tailwind brand usage guidelines](https://tailwindcss.com/brand#usage)
- [ +] I have read and followed the [contribution guidelines](https://github.com/aniftyco/awesome-tailwindcss/blob/master/.github/CONTRIBUTING.md)

add(tutorials): Framer Motion

---

README.md

| Fluid | https://github.com/barvian/fluid-tailwind |
Adds fluid `clamp()` versions of every built-in utility.
---

add(plugins): Fluid

---

README.md

| Dot & Grid Backgrounds | https://github.com/TheNaubit/tailwind-dot-grid-backgrounds |
Adds `bg-grid` and `bg-dot` classes to add easy-to-customize grid and dot pattern backgrounds with just CSS.
---

add(plugins): Dot & Grid Backgrounds

---

README.md

| VS2022-Editor-Support-for-Tailwind-CSS | https://github.com/theron-wang/VS2022-Editor-Support-for-Tailwind-CSS |
Unofficial VS2022 Tailwind CSS extension for IntelliSense, linting, sorting, and more to enhance the development experience in Visual Studio 2022.
---

add(extensions): VS2022 Editor Support

---

README.md

| tailwindcss-quantity-queries | [_Resource link here_](https://github.com/skttl/tailwindcss-quantity-queries) |
A plugin for adding variants for using quantity queries with Tailwind CSS
---

add(plugin): Quantity Queries

---

README.md

I really enjoyed using this project, nice work! Caught a couple of typos in the README.md though 😛

Fix typos 

---

README.md

| _tailwindcss-px-to-viewport_ | _[tailwindcss-px-to-viewport](https://github.com/the-lemonboy/tailwindcss-px-to-viewport)_ |
_Tailwind CSS plugin that automatically converts **px** unit properties to viewport units **vw** or **vh**._
---

add(plugin): Tailwind CSS px to viewport

---

.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md
README.md

It's been a while since our last clean up, it was long overdue! This pull request slightly updates the contribution guidelines, the template, and most importantly, the list.
- A _lot_ of links have been removed. Most of them were out-of-date (still on Tailwind CSS v3, some even on v2 or v1!), a few of them were hijacked or down, and some were simply no longer useful.
- I removed the "starters and theme" and "learning" categories. Both of them had very outdated links, often being more than 6 years old. There were barely enough resources there to justify those categories.
- I don't think it makes sense anymore to have the plugin category first. It was useful until Tailwind CSS v4, but this version is so much more flexible that the needs for plugins basically vanished. I put it last for this …

chore: clean up
